name: Notify Slack about new PR

on:
  pull_request:
    types: [opened]

jobs:
  Notify:
    name: Send Slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: |
          PR=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
          PR_URL="https://github.com/$GITHUB_REPOSITORY/pull/$PR"

          cat > /tmp/payload.json <<EOF
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "New pull request in *${REPO}*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ">${TITLE}:\n>${PR_URL}"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Author: *@${USER}*"
                  }
                ]
              }
            ]
          }
          EOF
          curl -X POST -H 'Content-type: application/json' -d @/tmp/payload.json "${SLACK_WEBHOOK_URL}"
        env:
          USER: ${{ github.actor }}
          REPO: ${{ github.repository }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
