name: Validate definitions

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  Convert:
    name: Convert definitions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 🐍
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install python dependencies
        run: pip install pre-commit

      - name: Run validation
        run: pre-commit run --all-files
