name: Validate definitions

on:
  workflow_call:

jobs:
  Validate:
    name: Validate definitions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4.2.1

      - name: Set up Python 🐍
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 #v5.2.0
        with:
          python-version: 3.11

      - name: Install definition tooling
        run: pip install ioxio-data-product-definition-tooling

      - name: Run validation
        run: validate-definitions ./DataProducts
